#!/usr/bin/env node
import { mkdir, writeFile } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"

const upstreamThemeUrl =
  "https://raw.githubusercontent.com/anomalyco/opencode/dev/packages/opencode/src/cli/cmd/tui/context/theme/opencode.json"

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const outputPath = path.join(root, "themes", "opencode-color-theme.json")

const response = await fetch(upstreamThemeUrl)
if (!response.ok) {
  throw new Error(`Failed to fetch OpenCode theme: ${response.status} ${response.statusText}`)
}

const source = await response.json()
const theme = resolveOpenCodeTheme(source, "dark")
const c = theme

const vscodeTheme = {
  $schema: "vscode://schemas/color-theme",
  name: "OpenCode",
  type: "dark",
  semanticHighlighting: true,
  colors: {
    foreground: c.text,
    disabledForeground: c.textMuted,
    descriptionForeground: c.textMuted,
    errorForeground: c.error,
    focusBorder: c.borderActive,
    "selection.background": c.selection,
    "textBlockQuote.background": c.backgroundPanel,
    "textBlockQuote.border": c.border,
    "textCodeBlock.background": c.backgroundPanel,
    "textLink.activeForeground": c.primaryActive,
    "textLink.foreground": c.primary,
    "textPreformat.foreground": c.markdownCode,
    "button.background": c.primary,
    "button.foreground": c.background,
    "button.hoverBackground": c.primaryActive,
    "button.secondaryBackground": c.backgroundElement,
    "button.secondaryForeground": c.text,
    "button.secondaryHoverBackground": c.backgroundHover,
    "dropdown.background": c.backgroundPanel,
    "dropdown.border": c.border,
    "dropdown.foreground": c.text,
    "input.background": c.backgroundPanel,
    "input.border": c.borderSubtle,
    "input.foreground": c.text,
    "input.placeholderForeground": c.textMuted,
    "inputOption.activeBackground": c.backgroundHover,
    "inputOption.activeBorder": c.primary,
    "inputValidation.errorBackground": c.diffRemovedBg,
    "inputValidation.errorBorder": c.error,
    "inputValidation.infoBackground": c.diffAddedBg,
    "inputValidation.infoBorder": c.info,
    "inputValidation.warningBackground": c.warningBg,
    "inputValidation.warningBorder": c.warning,
    "scrollbar.shadow": `${c.background}00`,
    "scrollbarSlider.activeBackground": `${c.borderActive}cc`,
    "scrollbarSlider.background": `${c.selection}99`,
    "scrollbarSlider.hoverBackground": `${c.border}cc`,
    "badge.background": c.backgroundElement,
    "badge.foreground": c.primary,
    "progressBar.background": c.primary,
    "list.activeSelectionBackground": c.backgroundHover,
    "list.activeSelectionForeground": c.text,
    "list.dropBackground": `${c.diffAddedBg}99`,
    "list.focusBackground": c.backgroundElement,
    "list.focusForeground": c.text,
    "list.highlightForeground": c.primary,
    "list.hoverBackground": c.backgroundPanel,
    "list.hoverForeground": c.text,
    "list.inactiveSelectionBackground": c.backgroundElement,
    "list.inactiveSelectionForeground": c.text,
    "list.warningForeground": c.warning,
    "list.errorForeground": c.error,
    "activityBar.background": c.background,
    "activityBar.border": c.backgroundHover,
    "activityBar.foreground": c.primary,
    "activityBar.inactiveForeground": c.textMuted,
    "activityBarBadge.background": c.primary,
    "activityBarBadge.foreground": c.background,
    "sideBar.background": c.background,
    "sideBar.border": c.backgroundHover,
    "sideBar.foreground": c.text,
    "sideBarSectionHeader.background": c.backgroundPanel,
    "sideBarSectionHeader.border": c.backgroundHover,
    "sideBarTitle.foreground": c.text,
    "editorGroup.border": c.backgroundHover,
    "editorGroup.dropBackground": `${c.diffAddedBg}99`,
    "editorGroupHeader.tabsBackground": c.background,
    "editorGroupHeader.tabsBorder": c.backgroundHover,
    "tab.activeBackground": c.backgroundPanel,
    "tab.activeBorderTop": c.primary,
    "tab.activeForeground": c.text,
    "tab.border": c.backgroundHover,
    "tab.inactiveBackground": c.background,
    "tab.inactiveForeground": c.textMuted,
    "tab.unfocusedActiveForeground": c.text,
    "tab.unfocusedInactiveForeground": c.borderActive,
    "editor.background": c.background,
    "editor.foreground": c.text,
    "editor.findMatchBackground": `${c.primary}55`,
    "editor.findMatchBorder": c.primary,
    "editor.findMatchHighlightBackground": `${c.primary}22`,
    "editor.lineHighlightBackground": c.backgroundPanel,
    "editor.lineHighlightBorder": `${c.backgroundHover}00`,
    "editor.selectionBackground": c.selection,
    "editor.selectionHighlightBackground": `${c.selection}88`,
    "editor.wordHighlightBackground": c.backgroundHover,
    "editor.wordHighlightStrongBackground": c.borderSubtle,
    "editorBracketHighlight.foreground1": c.primary,
    "editorBracketHighlight.foreground2": c.accent,
    "editorBracketHighlight.foreground3": c.info,
    "editorBracketHighlight.foreground4": c.success,
    "editorBracketHighlight.foreground5": c.syntaxType,
    "editorBracketHighlight.foreground6": c.warning,
    "editorCursor.foreground": c.primary,
    "editorError.foreground": c.error,
    "editorGroupHeader.noTabsBackground": c.background,
    "editorGutter.addedBackground": c.success,
    "editorGutter.background": c.background,
    "editorGutter.deletedBackground": c.error,
    "editorGutter.modifiedBackground": c.primary,
    "editorIndentGuide.activeBackground1": c.borderActive,
    "editorIndentGuide.background1": c.backgroundHover,
    "editorLineNumber.activeForeground": c.primary,
    "editorLineNumber.foreground": c.borderActive,
    "editorOverviewRuler.border": c.background,
    "editorWarning.foreground": c.warning,
    "editorWidget.background": c.backgroundPanel,
    "editorWidget.border": c.border,
    "editorWidget.foreground": c.text,
    "peekView.border": c.border,
    "peekViewEditor.background": c.background,
    "peekViewEditor.matchHighlightBackground": `${c.primary}44`,
    "peekViewResult.background": c.backgroundPanel,
    "peekViewResult.matchHighlightBackground": `${c.primary}44`,
    "peekViewTitle.background": c.backgroundElement,
    "panel.background": c.background,
    "panel.border": c.backgroundHover,
    "panelTitle.activeBorder": c.primary,
    "panelTitle.activeForeground": c.text,
    "panelTitle.inactiveForeground": c.textMuted,
    "statusBar.background": c.background,
    "statusBar.border": c.backgroundHover,
    "statusBar.debuggingBackground": c.accent,
    "statusBar.debuggingForeground": c.background,
    "statusBar.foreground": c.text,
    "statusBar.noFolderBackground": c.background,
    "statusBarItem.prominentBackground": c.backgroundElement,
    "statusBarItem.remoteBackground": c.primary,
    "statusBarItem.remoteForeground": c.background,
    "titleBar.activeBackground": c.background,
    "titleBar.activeForeground": c.text,
    "titleBar.border": c.backgroundHover,
    "titleBar.inactiveBackground": c.background,
    "titleBar.inactiveForeground": c.textMuted,
    "menu.background": c.backgroundPanel,
    "menu.foreground": c.text,
    "menu.selectionBackground": c.backgroundHover,
    "menu.selectionForeground": c.text,
    "menubar.selectionBackground": c.backgroundPanel,
    "menubar.selectionForeground": c.text,
    "notificationCenter.border": c.border,
    "notificationCenterHeader.background": c.backgroundPanel,
    "notificationToast.border": c.border,
    "notifications.background": c.backgroundPanel,
    "notifications.border": c.border,
    "notifications.foreground": c.text,
    "notificationsErrorIcon.foreground": c.error,
    "notificationsInfoIcon.foreground": c.info,
    "notificationsWarningIcon.foreground": c.warning,
    "quickInput.background": c.backgroundPanel,
    "quickInput.foreground": c.text,
    "quickInputTitle.background": c.backgroundElement,
    "pickerGroup.border": c.backgroundHover,
    "pickerGroup.foreground": c.primary,
    "terminal.background": c.background,
    "terminal.foreground": c.text,
    "terminal.ansiBlack": c.background,
    "terminal.ansiBlue": c.secondary,
    "terminal.ansiBrightBlack": c.borderActive,
    "terminal.ansiBrightBlue": c.secondary,
    "terminal.ansiBrightCyan": c.info,
    "terminal.ansiBrightGreen": c.success,
    "terminal.ansiBrightMagenta": c.accent,
    "terminal.ansiBrightRed": c.error,
    "terminal.ansiBrightWhite": c.text,
    "terminal.ansiBrightYellow": c.syntaxType,
    "terminal.ansiCyan": c.info,
    "terminal.ansiGreen": c.success,
    "terminal.ansiMagenta": c.accent,
    "terminal.ansiRed": c.error,
    "terminal.ansiWhite": c.text,
    "terminal.ansiYellow": c.warning,
    "terminalCursor.foreground": c.primary,
    "breadcrumb.background": c.background,
    "breadcrumb.foreground": c.textMuted,
    "breadcrumb.focusForeground": c.text,
    "breadcrumb.activeSelectionForeground": c.primary,
    "gitDecoration.addedResourceForeground": c.success,
    "gitDecoration.deletedResourceForeground": c.error,
    "gitDecoration.ignoredResourceForeground": c.borderActive,
    "gitDecoration.modifiedResourceForeground": c.primary,
    "gitDecoration.untrackedResourceForeground": c.info,
    "diffEditor.insertedTextBackground": `${c.diffAddedBg}99`,
    "diffEditor.removedTextBackground": `${c.diffRemovedBg}99`,
    "diffEditorGutter.insertedLineBackground": c.diffAddedLineNumberBg,
    "diffEditorGutter.removedLineBackground": c.diffRemovedLineNumberBg,
    "settings.headerForeground": c.primary,
    "settings.modifiedItemIndicator": c.primary,
    "welcomePage.progress.background": c.backgroundElement,
    "welcomePage.progress.foreground": c.primary,
  },
  tokenColors: [
    rule(["comment", "punctuation.definition.comment"], c.syntaxComment, "italic"),
    rule(["keyword", "storage.type", "storage.modifier", "support.type.property-name.css"], c.syntaxKeyword, "italic"),
    rule(["entity.name.function", "support.function", "meta.function-call", "variable.function"], c.syntaxFunction),
    rule(["string", "constant.other.symbol", "markup.inline.raw.string"], c.syntaxString),
    rule(["constant.numeric", "constant.language.boolean", "constant.language.null", "constant.language.undefined"], c.syntaxNumber),
    rule(["entity.name.type", "entity.name.class", "entity.name.struct", "support.class", "support.type", "meta.type.annotation"], c.syntaxType),
    rule(["variable", "variable.other.readwrite", "entity.name.variable"], c.syntaxVariable),
    rule(["variable.other.property", "support.variable.property", "meta.object-literal.key", "entity.other.attribute-name"], c.syntaxOperator),
    rule(["keyword.operator", "punctuation.separator", "punctuation.accessor"], c.syntaxOperator),
    rule(["punctuation", "meta.brace", "meta.delimiter"], c.syntaxPunctuation),
    rule(["markup.heading", "markup.heading entity.name"], c.markdownHeading, "bold"),
    rule("markup.underline.link", c.markdownLink),
    rule("markup.quote", c.markdownBlockQuote, "italic"),
    rule(["markup.inserted", "markup.diff.header.to-file"], c.success),
    rule(["markup.deleted", "markup.diff.header.from-file"], c.error),
    rule("invalid", c.error),
  ],
  semanticTokenColors: {
    class: c.syntaxType,
    enum: c.syntaxType,
    function: c.syntaxFunction,
    interface: c.syntaxType,
    keyword: c.syntaxKeyword,
    method: c.syntaxFunction,
    namespace: c.syntaxType,
    number: c.syntaxNumber,
    operator: c.syntaxOperator,
    parameter: c.syntaxVariable,
    property: c.syntaxOperator,
    string: c.syntaxString,
    struct: c.syntaxType,
    type: c.syntaxType,
    typeParameter: c.syntaxType,
    variable: c.syntaxVariable,
  },
}

await mkdir(path.dirname(outputPath), { recursive: true })
await writeFile(outputPath, `${JSON.stringify(vscodeTheme, null, 2)}\n`)
console.log(`Generated ${path.relative(root, outputPath)} from ${upstreamThemeUrl}`)

function resolveOpenCodeTheme(source, mode) {
  const defs = source.defs ?? {}

  const resolve = (value, chain = []) => {
    if (typeof value === "string") {
      if (value.startsWith("#")) return value.toLowerCase()
      if (chain.includes(value)) throw new Error(`Circular color reference: ${[...chain, value].join(" -> ")}`)
      const next = defs[value] ?? source.theme[value]
      if (next === undefined) throw new Error(`Unknown OpenCode color reference: ${value}`)
      return resolve(next, [...chain, value])
    }
    if (value && typeof value === "object" && mode in value) return resolve(value[mode], chain)
    throw new Error(`Unsupported OpenCode color value: ${JSON.stringify(value)}`)
  }

  const resolved = Object.fromEntries(Object.entries(source.theme).map(([key, value]) => [key, resolve(value)]))

  return {
    ...resolved,
    selection: resolve("darkStep5"),
    primaryActive: resolve("darkStep10"),
    backgroundHover: resolve("darkStep4"),
    warningBg: "#2d281f",
  }
}

function rule(scope, foreground, fontStyle) {
  return {
    scope,
    settings: {
      foreground,
      ...(fontStyle ? { fontStyle } : {}),
    },
  }
}
